[profile.default]
solc_version = '0.8.17'
optimizer = true
optimizer_runs = 2383
via_ir = true
out = 'out'
test = 'test'
src = 'src'
libs = ['lib', 'node_modules']
gas_reports = ['*']

fs_permissions = [{ access = "read", path = "./addresses"}, { access = "read", path = "./chainConfigs"}, { access = "read", path = "./package.json" }]

[etherscan]
optimism = { key = "$OPT_ETHERSCAN_API_KEY" }
base = { key = "ANY_KEY_IS_OKAY" }

zora_mainnet = { key = "", chain = 7777777, url = "https://explorer.zora.energy/api\\?" }
zora_testnet = { key = "", chain = 999, url = "https://explorer.testnet.zora.energy/api\\?" }

pgn = { key = "", chain = 7777777, url = "https://explorer.publicgoods.network/api\\?" }
pgn_sepolia = { key = "", chain = 7777777, url = "https://explorer.sepolia.publicgoods.network/api\\?" }

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
goerli = "https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_KEY}"

# for optimism, since we are just using this for deployment/fork testing,
# we can use these since they're lower volume.

optimism = "https://mainnet.optimism.io"
optimism_goerli = "https://goerli.optimism.io"

zora = "https://rpc.zora.energy"
zora_goerli = "https://testnet.rpc.zora.energy"

base = "https://developer-access-mainnet.base.org"
base_goerli = "https://goerli.base.org"

pgn = "https://rpc.publicgoods.network"
pgn_sepolia = "https://sepolia.publicgoods.network"
